language: elixir
matrix:
  include:
    - elixir: 1.5
      otp_release: 18.3
      services: docker
    - elixir: 1.5
      otp_release: 19.2
      services: docker
    - elixir: 1.6
      otp_release: 20.2
      services: docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - mix credo --strict
  - mix test
after_script:
  - mix inch.report
