language: elixir

# Compatibility between Elixir and Erlang/OTP
# https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html
matrix:
  include:
    - elixir: 1.5
      otp_release: 18.1
      services: docker
    - elixir: 1.5
      otp_release: 20.3
      services: docker
    - elixir: 1.6
      otp_release: 19.0
      services: docker
    - elixir: 1.6
      otp_release: 20.3
      services: docker

before_script:
  - chmod -R g-w test/fixtures # y u no work as expected travis?

script:
  - mix credo --strict
  - mix test --exclude functional
  - mix test --only functional

after_script:
  - mix inch.report
