name: CI

on:
  - push
  - pull_request

jobs:
  # credo:

  # format:

  test:
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.erlang }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: "23.0"
            elixir: "1.10.3"
          - erlang: "22.3"
            elixir: "1.9.4"
          - erlang: "21.3"
            elixir: "1.8.2"
          - erlang: "20.3.1"
            elixir: "1.7.4"
          - erlang: "19.3"
            elixir: "1.6.6"
          - erlang: "18.3"
            elixir: "1.5.3"

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run unit tests
        run: mix test --trace --exclude functional

      - name: Run functional tests
        run: mix test --trace --only functional
